work_dir: ./work_dir/recognition/ntu-xview/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: /ssd/xyliu/data/NTU/health/train_data.npy
  label_path: /ssd/xyliu/data/NTU/health/train_data_labels.npy
test_feeder_args:
  data_path: /ssd/xyliu/data/NTU/health/test_data.npy
  label_path: /ssd/xyliu/data/NTU/health/test_data_labels.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 8
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'customer settings'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 80

